### ISSUE TITLE
git pull fails with fatal: protocol error: bad line length character: Inva

### ISSUE THREAD

**Issue by ghost** [tkisme/gogs-openshift#3] opened 2016-02-22 12:28 UTC
I can't clone a remote repository in my openshift-gogs environment via ssh, I get the error: fatal: protocol error: bad line length character: Inva. 

Openshifts runs on a git checkout the following script: oo-trap-user

```
# replace leading tilde (~) with user's home path
realpath = os.path.expanduser(thearg)
if not realpath.startswith(config['GEAR_BASE_DIR']):
    syslog.syslog("Invalid repository: not in openshift_root (%s) - %s: (%s)" %
                  (config['GEAR_BASE_DIR'], thearg, realpath))
    print "Invalid repository %s: not in application root" % thearg
    sys.exit(3)
```

The repo clone must start with "~" to get it working. 

Example: ssh://56af47fb33866adbdb00007e@gogs-test.openshift.local.de:tools/test.git don't works
                ssh://56af47fb33866adbdb00007e@gogs-test.openshift.local.de/~/app-root/data/gogs-repositories/tools/test.git works

Is is possible to change the ssh checkout url?

**Comment by tkizm1** [comment] 2016-02-27 18:35
I think this is the issue of rhc command line tool
update rhc and try again

```
rhc app create diy diy-0.1 --from-code https://github.com/tkisme/gogs-openshift
```

**Comment by ghost** [comment] 2016-02-29 06:54
To get that clear, gogs is running :). 

But I can't clone repos out of there. With the provided ssh links. This oo-trap-user is part of the openshift not rhc. Also I setup the cartridge with rhc version: 1.38.4 (latest)

**Comment by tkizm1** [comment] 2016-03-01 02:23
this is not an issue of this repo,so I close it

**Comment by ghost** [comment] 2016-03-01 07:17
So this is still a bug, all features of gogs are not running in openshift correctly right now! (I would say a core functionality)

**Comment by tkizm1** [comment] 2016-03-02 06:36
I can not reproduce this bug 
Update: gogs is installed and all features of gogs are running in openshift correctly right now!
[demo](https://diy-gaetk.rhcloud.com/install)
You are to blame for the error because this page appears.
![700db5cd-0b14-4e5e-9d48-10bd1d0dbe12](https://cloud.githubusercontent.com/assets/5886048/13452851/a5e06070-e086-11e5-843d-a08b928288b4.png)

and that bug is not for me show me your version of rhc

> $ rhc --version

**Comment by tkizm1** [comment] 2016-03-02 07:23
Update: Just a waste of time

```
➜  ~ rhc app create diy diy-0.1 --from-code https://github.com/tkisme/gogs-openshift
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Application Options
-------------------
Domain:      gaetk
Cartridges:  diy-0.1
Source Code: https://github.com/tkisme/gogs-openshift
Gear Size:   default
Scaling:     no

Creating application 'diy' ... done

  Disclaimer: This is an experimental cartridge that provides a way to try unsupported languages, frameworks, and middleware on OpenShift.
Application is already stopped

Waiting for your DNS name to be available ... done

Cloning into 'diy'...
Warning: Permanently added the RSA host key for IP address '52.90.146.184' to the list of known hosts.

Your application 'diy' is now available.

  URL:        http://diy-gaetk.rhcloud.com/
  SSH to:     56d694302d5271687500017d@diy-gaetk.rhcloud.com
  Git remote: ssh://56d694302d5271687500017d@diy-gaetk.rhcloud.com/~/git/diy.git/
  Cloned to:  /Users/tk/diy

Run 'rhc show-app diy' for more details about your app.
➜  ~ rhc --version
rhc 1.38.4


```

**Comment by ghost** [comment] 2016-03-02 08:48
so thats still not my problem. 

The problem is that you can't checkout gits you created in the application with ssh. 
Can you checkout gits you created in gogs with ssh?

Example: 
Here is a test repo I created:
![copy-url](https://cloud.githubusercontent.com/assets/10142082/13455003/230b6152-e05b-11e5-8339-592580d3d44c.png)

That's the output when I try to clone the new created repo in gogs. (Not the cartridge repo!).
![bug](https://cloud.githubusercontent.com/assets/10142082/13455009/2d003dae-e05b-11e5-8fac-7be30c3d5375.png)

Openshift runs on a git checkout the following script: oo-trap-user ( I am not an admin in the openshift just a normal user and admin rights in my namespace) 

```
# replace leading tilde (~) with user's home path
realpath = os.path.expanduser(thearg)
if not realpath.startswith(config['GEAR_BASE_DIR']):
    syslog.syslog("Invalid repository: not in openshift_root (%s) - %s: (%s)" %
                  (config['GEAR_BASE_DIR'], thearg, realpath))
print "Invalid repository %s: not in application root" % thearg
sys.exit(3)
```

The repo clone must start with "~" to get it working.

Example: ssh://56af47fb33866adbdb00007e@gogs-test.openshift.local.de:tools/test.git don't works
ssh://56af47fb33866adbdb00007e@gogs-test.openshift.local.de/~/app-root/data/gogs-repositories/tools/test.git works

Is is possible to change the ssh checkout url?

**Comment by tkizm1** [comment] 2016-03-02 13:25
SSH will never be used on it,because port 22 is used by ssh client and we can not override system config.

```
$ ssh://56af47fb33866adbdb00007e@gogs-test.openshift.local.de
```

That point to home of user 56af47fb33866adbdb00007e which means ~

```
$ ssh://56af47fb33866adbdb00007e@gogs-test.openshift.local.de:tools/test.git
```

That point to ~/tools/test.git not ~/app-root/data/gogs-repositories/tools/test.git

**Comment by ghost** [comment] 2016-03-02 15:22
We have no need to reconfigure SSH, its running on Port 22 and everything is fine.

The only thing we need to change is the ssh clone URL (My start question). From 

```
$ ssh://56af47fb33866adbdb00007e@gogs-test.openshift.local.de:vschmi/test.git
```

to 

```
$ git clone ssh://56af47fb33866adbdb00007e@gogs-test.openshift.local.de/~/app-root/data/gogs-repositories/vschmi/test.git /tmp/testasdsad
Cloning into '/tmp/testasdsad'...
remote: Counting objects: 3, done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (3/3), done.
Checking connectivity... done.
```

If I try to clone the git like this it works. 
So is is possible to change the ssh checkout url?

**Comment by tkizm1** [comment] 2016-03-04 06:47
[rtfm](https://gogs.io/docs/advanced/configuration_cheat_sheet)

**Comment by ghost** [comment] 2016-03-04 08:50
Okay you don't want to help me.

I read the fucking manual bevore I opened this issue, because it's not possible ATM. 

Is it possible that an developer changes makes it possible that admin user in gogs can change  the SSH clone URL that openshift is fully supported, as you said in your own thread?

**Comment by tkizm1** [comment] 2016-03-05 16:07
openshift open only one port in variable OPENSHIFT_DIY_PORT

```
$ env|grep -i port
```

For example openshift open port 8080 for me 

```
OPENSHIFT_DIY_PORT=8080
```

that means I can only use ssh and http which redirect to 8080 port,there is no more port we can use.(If anyone knows,please send email to me)

So,we can only use ssh by default.But gogs can edit path to gogs

```
; Root path of SSH directory, default is '~/.ssh', but you have to use '/home/git/.ssh'.
SSH_ROOT_PATH = 
```

Still fail to change ssh excute path,default ssh of system will only excute file in  ~/.ssh not SSH_ROOT_PATH

Update 

```
; Domain name to be exposed in clone URL
SSH_DOMAIN = %(DOMAIN)s
```

may be is will work?!
 still get error
[tried this](https://github.com/gogits/gogs/issues/545)
and if i change domain,it will never works,anyway [you can change it](https://github.com/gogits/gogs/blob/master/models/repo.go#L314)
55f16afd7628e1b6b9000196@gogs-gaetk.rhcloud.com~/app-root/data/gogs-repositories/:model/appfortest

**Closed as completed** 2016-03-06 02:04 UTC

**Comment by ghost** [comment] 2016-03-06 08:00
That works? The SSH_domain will be exposed with an : at the end and I tested that this did not work. :( 
But I can't try it right now, I have to wait till Monday.

**Comment by tkizm1** [comment] 2016-03-06 13:05
like I said it will become 

```
55f16afd7628e1b6b9000196@gogs-gaetk.rhcloud.com~/app-root/data/gogs-repositories/:model/appfortest
```

**Comment by tkizm1** [comment] 2016-03-06 13:14
Before you leave a new comment, I said
**and if i change domain,it will never works,anyway [you can change it](https://github.com/gogits/gogs/blob/master/models/repo.go#L314)**
please read my comment closely before you leave new comment ...
